# Generated by Django 3.1.1 on 2020-09-15 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('spell_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mana_cost', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cooldown', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('casting_school', models.CharField(choices=[('HOLY', 'HOLY'), ('SHADOW', 'SHADOW'), ('FIRE', 'FIRE'), ('ARCANE', 'ARCANE')], default='', max_length=10)),
                ('cast_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dps_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('healing_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_atonement', models.BooleanField(default=False)),
                ('atonement_duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('spell_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mana_cost', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cooldown', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('casting_school', models.CharField(choices=[('HOLY', 'HOLY'), ('SHADOW', 'SHADOW'), ('FIRE', 'FIRE'), ('ARCANE', 'ARCANE')], default='', max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('initial_hit_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_per_tick', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baseline_tick_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('end_of_duration_tick', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_gcds', models.IntegerField(default=0)),
                ('total_healing', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('total_damage', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('raiders_healing_received_list', models.CharField(max_length=120, validators=[django.core.validators.int_list_validator])),
            ],
            options={
                'ordering': ('report_id',),
            },
        ),
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('buff_id', models.IntegerField(default=0, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='buff_icons')),
                ('affects_stat', models.CharField(blank=True, choices=[('CRIT', 'CRIT'), ('HASTE', 'HASTE'), ('MASTERY', 'MASTERY'), ('VERS', 'VERS')], default='', max_length=10)),
                ('max_stacks', models.IntegerField(default=1)),
                ('max_duration', models.IntegerField(default=0)),
                ('is_permanent', models.BooleanField(default=False)),
                ('procs_from', models.CharField(choices=[('RPPM', 'RPPM'), ('ANY_SPELL', 'ANY_SPELL'), ('DOT', 'DOT')], max_length=10)),
                ('rppm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('affects_spell', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affects_spell', to='web.cast')),
                ('caused_by_spell', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='caused_by_spell', to='web.cast')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReportBuffValue',
            fields=[
                ('buff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.buff')),
                ('total_healing_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('total_damage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('simulation_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.simulationreport')),
            ],
        ),
    ]
